### ISSUE TITLE
Change PC Saves Hotline number to +1...

### ISSUE THREAD

**Issue by choquette33** [systers/FirstAide-Android#274]
Currently the number that is dialed goes to 001408... which doesn't seem to work. Probably best to use the +1408...

**Comment by rohands** [comment]
@sandarumk can I fix this?

**Comment by sandarumk** [comment]
yeah. Fix this and the other unclaimed issue with the countries.

**Comment by AkankshaBodhankar** [comment]
Is the same change required for PCSA web as well?

**Comment by sandarumk** [comment]
I think it does @AkankshaBodhankar .

**Comment by top-gun007** [comment]
is some one working on this issue? if not i can fix this

**Comment by sandarumk** [comment]
@rohands is on it.

**Comment by top-gun007** [comment]
@sandarumk can you please tell about issues which are free and no one is working as most of them are assigned

**Comment by sandarumk** [comment]
issues which are free are tagged free.

**Comment by top-gun007** [comment]
my bad thanks @sandarumk

**Comment by sandarumk** [comment]
@rohands are you still working on this or else we can assign it to @top-gun007 ?

**Comment by rohands** [comment]
@sandarumk please assign it to @top-gun007

**Comment by sandarumk** [comment]
@top-gun007 Please go ahead with this.

**Comment by ashu-dadhich** [comment]
thanks for the opportunity @rohands , @sandarumk

**Comment by sandarumk** [comment]
merged.
