### ISSUE TITLE
Transition slides down instead of right on Contact Post Staff screen

### ISSUE THREAD

**Issue by choquette33** [systers/FirstAide-Android#275]
On Get Help Now > Contact Post Staff...

When I hit the right arrow I expect the screen to slide to the right, however currently the screen transitions to the Contact Other Staff page by sliding down from the top.

**Comment by rishimadhok** [comment]
Hi,
I can fix this issue and would like to do it if needed. Please let me know.

**Comment by sandarumk** [comment]
sure. you can do this.

**Comment by choquette33** [comment]
@rishimadhok Thanks! Take a look at the transitions overall and see that they feel natural and consistent. Since the users are Americans they are used to forward being to the right and backward being to the left. 

A button push should be a fast slide in from right. (Not from the top.)

A right arrow push should lead to a slide in from the right, a left arrow push should be a slide in from the left.

**Comment by rishimadhok** [comment]
@choquette33 Thank you so much for your feedback. I will take note of this and implement the changes required.

**Comment by saketkumar95** [comment]
@sandarumk Can i work on this?

**Comment by sandarumk** [comment]
@saketkumar95 please read the comments. It is being currently fixed by @rishimadhok . He has already sent a PR and we have given our comments on improving it. @rishimadhok we hope you are already on it. If you don't please inform us, so we can assign it to someone else who is interested.

**Comment by saketkumar95** [comment]
@sandarumk Sure. Do inform me if it will be free and please suggests some issues which are free right now.

**Comment by sandarumk** [comment]
@saketkumar95 free issues will be tagged "free".

**Comment by sandarumk** [comment]
Since the assignee didn't go forward with the suggestions for improvement and we have received no updates from him, reserving the task as GCI

**Comment by saketkumar95** [comment]
@sandarumk  Can i work on it?

**Comment by sandarumk** [comment]
No you can choose from other free tasks. this is allocated fro GCI.

**Comment by InfernoCoder** [comment]
I'd like to claim this issue for GCI.

**Comment by Yureien** [comment]
Hi, I would like to claim this for GCI.

**Comment by Yureien** [comment]
I fixed this and PR is #326.

**Comment by chamika** [comment]
@sandarumk The issue is fixed. This can be closed now after merging the PR #326

**Comment by sandarumk** [comment]
fixed via #326 as a GCI task.
