### ISSUE TITLE
Issue with Bystander Intervention fragment

### ISSUE THREAD

**Issue by pandilladivya** [systers/FirstAide-Android#289]
**Problem:**
Unable to view the complete page in **Bystander Intervention** fragment for mobile screens having  4.00-inch display and less.

![screenshot_2016-11-04-22-28-09](https://cloud.githubusercontent.com/assets/16818129/20028199/49e12cbc-a351-11e6-8e18-50f914f7fd7d.png)

And in landscape mode...

![image](https://cloud.githubusercontent.com/assets/16818129/20030361/81114874-a389-11e6-8663-fdedf74aa1d8.png)

Cannot Scroll down.

**Comment by pandilladivya** [comment]
@sandarumk can i fix this?

Thank You! :)

**Comment by sandarumk** [comment]
You can fix this after previous issue's improvement #287 . Also in the future please refrain from opening and getting assigned several issues at once without fixing the already opened and assigned issues. Or else we can always open the issues to fix by others as well.

**Comment by pandilladivya** [comment]
@sandarumk 

I'm actually waiting for you to give me a heads up to work on #287 and I've also completed with the code and ready to put a PR for that issue as well as this one

So if its okay then I'll put a PR right away :)

**Comment by sandarumk** [comment]
@pandilladivya if you haven't noticed both @rohands and I have have given heads up (3 days ago) to fix the issue and send the PR.

**Comment by pandilladivya** [comment]
@sandarumk

Sorry for being late
Please let me know if i should add icons to the main page as mentioned in the issue #287 

Kindly review #290 and #291 

Thank You :)

**Comment by sandarumk** [comment]
@pandilladivya Please keep the two issues separate and independent. Updates about other issues will be posted at the original issue, if we have.

**Comment by pandilladivya** [comment]
@sandarumk 

Kindly Review #293 
Thank You :)

**Comment by sandarumk** [comment]
Merged.
