### ISSUE TITLE
User Settings bar changes height on Name edit.

### ISSUE THREAD

**Issue by kisaacs** [systers/FirstAide-Android#292]
The middle-green "User Settings" bar increases in size to consume half the screen height after the keyboard pops up to edit the name:

1. Go to "User Settings" by clicking the wrench icon in the upper left of a fragment such as Circle of Trust:
![pcsa-android-usersettings](https://cloud.githubusercontent.com/assets/10036820/20040676/d0468bae-a418-11e6-8c72-0a3880e8ae02.png)

2. Click on "Name" to edit:
![pcsa-android-editnameinusersettings](https://cloud.githubusercontent.com/assets/10036820/20040681/dbe9d074-a418-11e6-8ff3-93583b821d22.png)
(Note the User Settings bar is already large here, but it's hard to see.)

3. Click off of the Name edit box to see the large "User Settings" bar at half height of the screen:
![pcsa-android-usersettingslargebar](https://cloud.githubusercontent.com/assets/10036820/20040686/efbf51dc-a418-11e6-95e6-1a0688675e76.png)

This issue was first pointed out to me by @rohands. I would like to assign this to @dewin017 as she has a fix.

**Comment by top-gun007** [comment]
is someone working on it?

**Comment by kisaacs** [comment]
It will be assigned to @dewin017 pending confirmation.

**Comment by sandarumk** [comment]
Since it is suggested by @rohands no confirmation is needed. @dewin017 can go ahead and submit a PR following the correct practices which are maintained in the repository.

**Comment by sandarumk** [comment]
Any update on this? Since this came up in #309 and similar issues being reported, I want to make sure the assignee is working on the issue.

**Comment by kisaacs** [comment]
Hi @sandarumk -- yes someone is still working on it.

**Comment by sandarumk** [comment]
@kisaacs It is better if that person can comment on here since there is no comment or PR from the assignee after this issue is opened.

**Comment by kisaacs** [comment]
@sandarumk Since this is stemming from GHC OSD, the assignee was waiting on me and I was for your approval until last week. Based on your response, I had to also contact another party and am waiting on their response.

**Comment by sandarumk** [comment]
Sure. Ask the assignee to confirm that she is fixing this by commenting on the issue or/and sending a PR.

**Comment by kisaacs** [comment]
@sandarumk I've been in contact with the GHC OSD team and while I haven't been able to contact @dewin017, team member @jaynies has said she would like to do it -- is this okay?

**Comment by sandarumk** [comment]
Sure. Ask her to confirm by commenting here.

**Comment by jaynies** [comment]
I'm confirming I'll work on this.

**Comment by sandarumk** [comment]
Fixed via #334 .
