### ISSUE TITLE
Inconsistent Alignment Of TextView in Bystander Intervention Fragment

### ISSUE THREAD

**Issue by pandilladivya** [systers/FirstAide-Android#294]
**Inconsistent alignment of textview** in bigger screens like tablets and Screens having more than 6 inch.

Text view is left aligned in Bystander Intervention Fragment where as all others are center aligned.

![screenshot_2016-11-13-02-06-05](https://cloud.githubusercontent.com/assets/16818129/20246300/e01f8078-a9d9-11e6-92c2-44139a83990a.png)

**Comment by pandilladivya** [comment]
@sandarumk 
Is this a valid issue?
If so can i fix this?

Thank You

**Comment by sandarumk** [comment]
Yes. Go ahead.

**Comment by sandarumk** [comment]
Merged.

**Comment by sandarumk** [comment]
Changing the Text View has impact on the other sections. Hence just changing the fragment_bystander.xml would have been enough.

**Comment by pandilladivya** [comment]
@sandarumk 
I apologize for my mistake
Will be careful from next time.
