### ISSUE TITLE
Send message to trusted contacts when power button is pressed a specific number of time. 

### ISSUE THREAD

**Issue by top-gun007** [systers/FirstAide-Android#295]
**Summary:**

- As in emergency situations user don't have to time to open the app and send message to his or her trusted contacts so I propose that there should be me feature like when the user presses the power button a specific number of times a message should be sent for help to his/her trusted contacts 

- We can also add a functionality which sends the message to users nearby to the victim(as help would arrive more quickly)

**Steps to reproduce:**
Create a background service which performs a specific action when power button is pressed a specific number of times.

**Comment by top-gun007** [comment]
@sandarumk should I start working on it.
Thank you

**Comment by sandarumk** [comment]
We currently do not need this functionality. Similar suggestions were put forward by previous students as well. I will tag these as a suggestion so we can discuss with along in another development phase.

**Comment by top-gun007** [comment]
ok @sandarumk thank you
