### ISSUE TITLE
Name validation at SignUp activity.

### ISSUE THREAD

**Issue by free4murad** [systers/FirstAide-Android#296]
I the user enter a few blank spaces instead of his name the app accepts the input saves the name in sharedprefrences as blank string.
![1-2](https://cloud.githubusercontent.com/assets/17262180/20279228/bd23dec6-aacd-11e6-881a-b6710986b31c.png)
![2-2](https://cloud.githubusercontent.com/assets/17262180/20279232/c0f874f8-aacd-11e6-9e83-9c112974e036.png)

There should be a mechanism to correct this bug.

**Comment by free4murad** [comment]
Should I make a PR for this.

**Comment by sandarumk** [comment]
Yeah please do. Please resolve the #297 with this too. Because both of these issues are related. In future when you report issues, if they are related, please report them as one.

**Comment by sandarumk** [comment]
Fixed with #299
