### ISSUE TITLE
Name validation in UserSettingsActivity

### ISSUE THREAD

**Issue by free4murad** [systers/FirstAide-Android#297]
In settings tab if the user changes his name and leaves the field blank or enters just a couple of spaces the name saved in sharedpreferences is a empty string or string containing spaces.
![1](https://cloud.githubusercontent.com/assets/17262180/20278748/dcdea932-aacb-11e6-96a0-e767c9028c8f.png)
![2](https://cloud.githubusercontent.com/assets/17262180/20278752/e05ac366-aacb-11e6-86b2-b7085faa4b40.png)

There should be a check to make sure that the name entered by the user is not an empty string.

**Comment by free4murad** [comment]
Should I make a PR for this.

**Comment by sandarumk** [comment]
Will be resolved with #296

**Comment by sandarumk** [comment]
Fixed.
