### ISSUE TITLE
Removing CircleIntro Dependency

### ISSUE THREAD

**Issue by codingblazer** [systers/FirstAide-Android#302]
Currently project has a following dependency which is used in CircleIntro.java for app tutorial - 

'com.github.paolorotolo:appintro:1.4.0'

It can be removed by using Viewpager instead. It can be done without effecting the UI and will reduce the apk size. Can i work on this if it's intended modification. Thanks.

**Comment by sandarumk** [comment]
yeah. Go ahead.

**Comment by sandarumk** [comment]
fixed.
