### ISSUE TITLE
General Styling Overhaul to look follow Original Design Documents

### ISSUE THREAD

**Issue by choquette33** [systers/FirstAide-Android#49]
Change the style to be reflective of the original design found in this document. https://drive.google.com/open?id=0B8cm8EBZg0GaZlNSdFpxeXJWelU (Mobile version starts at 0:58 of this video. 
- [ ] Change color codes to the following: 
  Main green color: 05D197
  Dark accent: 2DB58F
  Darker accent: 02845F
  White, for text: FFFFFF
  Main secondary yellow color: FFD590
  Dark accent: FFC25C
- [ ] Change font to Avenir Next, with "regular" as the main weight for content while "bold" used for buttons. (An alternative is Lato if we can't find a free one (https://www.google.com/fonts/specimen/Lato)
- [ ] Create opening screen with the following design:
  ![image](https://cloud.githubusercontent.com/assets/2973990/13091510/9a90659e-d4c9-11e5-8cc4-2f052d043a05.png)
- [ ] Add First Aide Title home page, (And generally add a title and subtitle to each screen as shown)
  ![image](https://cloud.githubusercontent.com/assets/2973990/13091790/d4a8b58c-d4ca-11e5-91a2-8d3592bd4d26.png)
- [ ] Adjust border radius on buttons to make them more square. Like this: 
  ![image](https://cloud.githubusercontent.com/assets/2973990/13092302/20a8be94-d4cd-11e5-97e0-83b2662eeb91.png)
- [ ] Adjust Hamburger appearance: 
  ![image](https://cloud.githubusercontent.com/assets/2973990/13092019/db391850-d4cb-11e5-9835-a2333a4efdfb.png)
- [ ] Add forward and back buttons to header. Like this: 
  ![image](https://cloud.githubusercontent.com/assets/2973990/13092339/67340094-d4cd-11e5-84d7-23154e46af75.png)
- [ ] Create Slide-in  side-bar menu that looks like this: 
  ![image](https://cloud.githubusercontent.com/assets/2973990/13092138/6d39fe4a-d4cc-11e5-8397-ca57505b0a7d.png)

With content like this, in this order: 
![image](https://cloud.githubusercontent.com/assets/2973990/13092249/e4adabc0-d4cc-11e5-97ce-042193add1eb.png)
- [ ] Change order of buttons to the following on home page: 
- Get help now
- Circle of trust
- Safety Tools
- Support Service
- Sexual Assault Awareness
- Policies and Glossary

**Comment by rosariorobinson** [comment]
@choquette33 is this design reflective of a web app? or the mobile app?  From the video it seems as this is a webapp.  Are we changing the whole scheme of this? Just give us some background on the changes. The team has been working with Sandi and there were specifics so we can be sure the team understands.

**Comment by choquette33** [comment]
This styling would be applied to iOS, Android, and the Web

**Comment by gondylife** [comment]
@choquette33 So the web app will be a direct reflection of the mobile apps? Anything extra?

**Comment by AkankshaBodhankar** [comment]
For the web app of PCSA
How can we implement the messaging feature of 'circle of trust'? Will email sending be replaced for that feature?

**Comment by calistus** [comment]
Use Systers mailing list for such questions

**Comment by choquette33** [comment]
@gondylife So sorry for missing your note so long ago.

**Comment by sandarumk** [comment]
@choquette33  The GSoC student for the project is @rohands. I asked him to create a mockup with the changes suggested by you in this issue. We will get back to you as soon as the new mockup is ready so you can validate what to be done.

**Comment by sandarumk** [comment]
@choquette33 Can you check whether this is fixed.

**Comment by choquette33** [comment]
@sandrarunk - the missing piece that stands out to me is the back and forward buttons. I think they are really important for an app with so many screens.

**Comment by choquette33** [comment]
@sandrarunk - The text first aide is missing from the splash screen.

**Comment by choquette33** [comment]
Also "First Aide" should replace "Peace Corps" be at the top of the slide in menu next to the logo. It also should link to the home screen. (which it doesn't do right now)

**Comment by rohands** [comment]
@choquette33 @sandarumk 
The UI Elements which you mentioned might have been missing from the current application but the current app's UI is built in accordance to mockups which has been approved by the team. 
In the mockup the splash screen does not have the text. Also, there are no back and forward buttons. If there is something wrong, please let me know. I'll fix them accordingly.

**Comment by rohands** [comment]
@choquette33 
Here is a link to mockups that was approved earlier.
<a>https://github.com/systers/PCSA-Android/blob/develop/docs/design/mockup.pdf</a>

**Comment by scandindian** [comment]
@choquette33 @rohands @sandarumk Hi. I think the app is great but UI needs to be more polished. The background of the drawer is too light to have white text on it and I guess it would be great the app is following material guideline. Can I work on it?

**Comment by sandarumk** [comment]
@heysadboy , welcome to the community. We do not hope to change the UI of the app and deviate from the mockup currently. If you have any suggestions or improvements, make a new issue. If that is acceptable, you will be asked to develop it. If not we will keep it in our suggestion list and discuss with Peace Corps in the next development phase. Please read the README file first. It will guide you to resources on how to report issues and make PRs.

**Comment by scandindian** [comment]
@sandarumk Thank you.

**Comment by sandarumk** [comment]
Fixed in last GSoC (2016) round.
